#!/bin/bash
DB="salfanet_radius"
USER="salfanet_user"
PASS="9wVyHRbaBxC7ylhBLr0K"

echo "=== 1. Add second NAS entry for 103.191.165.120 ==="
mysql -u $USER -p"$PASS" $DB -e "INSERT INTO nas (id, nasname, shortname, secret, type, isActive, ipAddress, auth_mode, createdAt, updatedAt) VALUES ('nas-public-ip', '103.191.165.120', 'dst-paska-public', 'secret123', 'mikrotik', 1, '103.191.165.120', 'radius', NOW(), NOW()) ON DUPLICATE KEY UPDATE isActive=1" 2>/dev/null
echo "Done"
echo
echo "=== Verify NAS entries ==="
mysql -u $USER -p"$PASS" $DB -e "SELECT id, nasname, shortname, secret, isActive FROM nas" 2>/dev/null
echo
echo "=== 2. Regenerate FreeRADIUS clients.d with BOTH IPs ==="
cat > /etc/freeradius/3.0/clients.d/nas-from-db.conf << 'EOF'
# Auto-generated by salfanet-radius - DO NOT EDIT MANUALLY

client nas_dst_paska {
    ipaddr = 192.168.54.1
    secret = secret123
    shortname = dst-paska
    nas_type = other
    require_message_authenticator = no
    limit_proxy_state = no
}

client nas_dst_paska_public {
    ipaddr = 103.191.165.120
    secret = secret123
    shortname = dst-paska-public
    nas_type = other
    require_message_authenticator = no
    limit_proxy_state = no
}

EOF
chown freerad:freerad /etc/freeradius/3.0/clients.d/nas-from-db.conf
echo "Done"
echo
echo "=== 3. Restart FreeRADIUS ==="
systemctl restart freeradius
sleep 2
echo
echo "=== 4. Test radtest simulating from 103.191.165.120 ==="
radtest server salfanet 127.0.0.1 0 testing123 2>&1 | tail -10
echo
echo "=== 5. Check FreeRADIUS log (last 10 lines) ==="
tail -10 /var/log/freeradius/radius.log 2>/dev/null
