#!/bin/bash
DB="salfanet_radius"
USER="salfanet_user"
PASS="9wVyHRbaBxC7ylhBLr0K"

echo "=== 1. Update NAS table: nasname 103.191.165.120 -> 192.168.54.1 ==="
mysql -u $USER -p"$PASS" $DB -e "UPDATE nas SET nasname='192.168.54.1' WHERE id='8a5f48c1-c825-4b96-9763-5c63c28fc950'" 2>/dev/null
echo "Done"
echo
echo "=== Verify NAS ==="
mysql -u $USER -p"$PASS" $DB -e "SELECT id, nasname, shortname, secret, isActive FROM nas" 2>/dev/null
echo
echo "=== 2. Regenerate FreeRADIUS clients.d ==="
# Trigger sync via API (but need auth). Let's do it manually.
cat > /etc/freeradius/3.0/clients.d/nas-from-db.conf << 'EOF'
# Auto-generated by salfanet-radius - DO NOT EDIT MANUALLY

client nas_dst_paska {
    ipaddr = 192.168.54.1
    secret = secret123
    shortname = dst-paska
    nas_type = other
    require_message_authenticator = no
    limit_proxy_state = no
}

EOF
chown freerad:freerad /etc/freeradius/3.0/clients.d/nas-from-db.conf
echo "Done"
echo
echo "=== 3. Restart FreeRADIUS ==="
systemctl restart freeradius
sleep 2
systemctl status freeradius | head -5
echo
echo "=== 4. Test radtest from 192.168.54.1 ==="
radtest server salfanet 192.168.54.1 0 secret123 2>&1
echo
echo "=== 5. Check FreeRADIUS log ==="
tail -5 /var/log/freeradius/radius.log 2>/dev/null
