package radius

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"time"

	"github.com/rs/zerolog/log"
	"gorm.io/gorm"
)

const nasClientsFile = "/etc/freeradius/3.0/clients.d/nas-from-db.conf"
const clientsConf = "/etc/freeradius/3.0/clients.conf"

var (
	syncMu          sync.Mutex
	lastReloadAt    time.Time
	reloadCooldown  = 3 * time.Second
	shortnameSanRe  = regexp.MustCompile(`[^a-zA-Z0-9_\-]`)
)

type nasRow struct {
	Nasname         string
	IPAddress       string
	Shortname       string
	Secret          string
	VpnClientId     *string
	VpnIp           *string
	IsRadiusServer  *bool
	VpnServerId     *string
	VpnServerName   *string
	VpnServerSubnet *string
}

// SyncNASClients regenerates /etc/freeradius/3.0/clients.d/nas-from-db.conf
// from the nas table (with vpn_clients/vpn_servers joins for CHR gateway entries),
// and reloads FreeRADIUS only if the file content actually changed.
//
// Safe to call from API handlers after Create/Update/Delete of a router.
func SyncNASClients(db *gorm.DB) error {
	syncMu.Lock()
	defer syncMu.Unlock()

	var rows []nasRow
	if err := db.Raw(`
		SELECT
			r.nasname           AS nasname,
			r.ipAddress         AS ip_address,
			r.shortname         AS shortname,
			r.secret            AS secret,
			r.vpnClientId       AS vpn_client_id,
			vc.vpnIp            AS vpn_ip,
			vc.isRadiusServer   AS is_radius_server,
			vs.id               AS vpn_server_id,
			vs.name             AS vpn_server_name,
			vs.subnet           AS vpn_server_subnet
		FROM nas r
		LEFT JOIN vpn_clients vc ON vc.id = r.vpnClientId
		LEFT JOIN vpn_servers vs ON vs.id = vc.vpnServerId
		WHERE r.isActive = 1
	`).Scan(&rows).Error; err != nil {
		return fmt.Errorf("load nas: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by salfanet-radius - DO NOT EDIT MANUALLY\n\n")

	type gwInfo struct {
		gatewayIP  string
		serverName string
		secrets    map[string]struct{}
	}
	gateways := map[string]*gwInfo{}

	for _, n := range rows {
		short := sanitizeShortname(firstNonEmpty(n.Shortname, n.Nasname))
		ip := firstNonEmpty(n.Nasname, n.IPAddress)
		if ip == "" || n.Secret == "" {
			continue
		}
		fmt.Fprintf(&buf, "client nas_%s {\n", short)
		fmt.Fprintf(&buf, "    ipaddr = %s\n", ip)
		fmt.Fprintf(&buf, "    secret = %s\n", n.Secret)
		fmt.Fprintf(&buf, "    shortname = %s\n", short)
		fmt.Fprintf(&buf, "    nas_type = other\n")
		fmt.Fprintf(&buf, "    require_message_authenticator = no\n")
		fmt.Fprintf(&buf, "    limit_proxy_state = no\n")
		fmt.Fprintf(&buf, "}\n\n")

		// Collect VPN gateway entries (CHR masquerade case).
		// Skip when this NAS itself IS the radius server (VPS).
		if n.VpnClientId != nil && *n.VpnClientId != "" &&
			n.VpnServerId != nil && *n.VpnServerId != "" &&
			(n.IsRadiusServer == nil || !*n.IsRadiusServer) {

			gwIP := deriveGatewayFromSubnet(strDeref(n.VpnServerSubnet))
			if gwIP == "" {
				continue
			}
			key := *n.VpnServerId
			gw, ok := gateways[key]
			if !ok {
				gw = &gwInfo{
					gatewayIP:  gwIP,
					serverName: sanitizeShortname(strDeref(n.VpnServerName)),
					secrets:    map[string]struct{}{},
				}
				gateways[key] = gw
			}
			gw.secrets[n.Secret] = struct{}{}
		}
	}

	if len(gateways) > 0 {
		buf.WriteString("# --- VPN Server Gateway Clients (CHR masquerade) ---\n\n")
		for _, gw := range gateways {
			if len(gw.secrets) > 1 {
				fmt.Fprintf(&buf, "# SKIPPED vpn_gw_%s: NAS behind it have %d different secrets\n\n", gw.serverName, len(gw.secrets))
				continue
			}
			var secret string
			for s := range gw.secrets {
				secret = s
			}
			fmt.Fprintf(&buf, "client vpn_gw_%s {\n", gw.serverName)
			fmt.Fprintf(&buf, "    ipaddr = %s\n", gw.gatewayIP)
			fmt.Fprintf(&buf, "    secret = %s\n", secret)
			fmt.Fprintf(&buf, "    shortname = vpn_gw_%s\n", gw.serverName)
			fmt.Fprintf(&buf, "    nas_type = other\n")
			fmt.Fprintf(&buf, "    require_message_authenticator = no\n")
			fmt.Fprintf(&buf, "    limit_proxy_state = no\n")
			fmt.Fprintf(&buf, "}\n\n")
		}
	}

	newContent := buf.Bytes()

	// Compare with current file — only reload if changed.
	current, _ := os.ReadFile(nasClientsFile)
	if bytes.Equal(bytes.TrimSpace(current), bytes.TrimSpace(newContent)) {
		log.Debug().Int("nas", len(rows)).Msg("freeradius: nas-from-db.conf already in sync")
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(nasClientsFile), 0755); err != nil {
		return fmt.Errorf("mkdir clients.d: %w", err)
	}
	if err := os.WriteFile(nasClientsFile, newContent, 0640); err != nil {
		return fmt.Errorf("write nas file: %w", err)
	}
	_ = exec.Command("chown", "freerad:freerad", nasClientsFile).Run()

	// Ensure clients.conf includes clients.d
	if conf, err := os.ReadFile(clientsConf); err == nil {
		if !bytes.Contains(conf, []byte("$INCLUDE clients.d/")) {
			f, ferr := os.OpenFile(clientsConf, os.O_APPEND|os.O_WRONLY, 0644)
			if ferr == nil {
				_, _ = f.WriteString("\n$INCLUDE clients.d/\n")
				_ = f.Close()
			}
		}
	}

	// Reload (with cooldown to coalesce bursts).
	if time.Since(lastReloadAt) < reloadCooldown {
		log.Info().Msg("freeradius: skipping reload (cooldown active)")
		return nil
	}
	lastReloadAt = time.Now()

	out, err := exec.Command("systemctl", "reload-or-restart", "freeradius").CombinedOutput()
	if err != nil {
		log.Error().Err(err).Str("out", string(out)).Msg("freeradius: reload failed")
		return fmt.Errorf("reload freeradius: %w (%s)", err, strings.TrimSpace(string(out)))
	}
	log.Info().Int("nas", len(rows)).Int("vpn_gw", len(gateways)).Msg("freeradius: nas-from-db.conf updated and service reloaded")
	return nil
}

func sanitizeShortname(s string) string {
	s = shortnameSanRe.ReplaceAllString(s, "_")
	if s == "" {
		s = "nas"
	}
	return s
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}

func strDeref(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// deriveGatewayFromSubnet: "10.20.30.0/24" → "10.20.30.1"
func deriveGatewayFromSubnet(subnet string) string {
	base := strings.SplitN(subnet, "/", 2)[0]
	parts := strings.Split(base, ".")
	if len(parts) != 4 {
		return ""
	}
	parts[3] = "1"
	return strings.Join(parts, ".")
}
